name: Tag

on:
  push:
    branches:
      - develop

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
        
      - name: Tag
        uses: actions/github-script@v5.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const packageJson = require("./package");
            await github.rest.git.createTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: `v${packageJson.version}`,
              message: `v${packageJson.version}`,
              object: context.sha,
              type: "commit",
              tagger: {
                name: context.actor,
                email: "dev@chronos.works"
              }
            });
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${packageJson.version}`,
              sha: context.sha,
            })
      